version: '3.4'

services:
    nginx:
        build:
            context: ./docker/nginx
            args:
                version: ${NGINX_VERSION}
        container_name: ${NGINX_CONTAINER_NAME}
        restart: unless-stopped
        ports:
            - ${NGINX_PORT}:80/tcp
        volumes:
            - ./:/www
        working_dir: /www
        depends_on:
          - php
        networks:
            - backend
            - frontend

    php:
        build:
            context: ./docker/php
            args:
                version: ${PHP_VERSION}
        container_name: ${PHP_CONTAINER_NAME}
        restart: unless-stopped
        ports:
            - "9000:9000/tcp"
        volumes:
            - ./:/www
        working_dir: /www
        depends_on:
          - mariadb
        networks:
            - backend

    mariadb:
        image: mariadb:${MARIADB_VERSION}
        container_name: ${MARIADB_CONTAINER_NAME}
        restart: unless-stopped
        ports:
          - "${MARIADB_PORT}:3306/tcp"
        volumes:
            - db_data:/var/lib/mysql
            - db_backup:/var/lib/backup
        environment:
            - MARIADB_ROOT_PASSWORD
            - MARIADB_DATABASE
            - MARIADB_USER
            - MARIADB_PASSWORD
        networks:
            - backend
            - frontend

volumes:
    db_data:
    db_backup:

networks:
    frontend:
        internal: false
    backend:
        internal: true
